---
title: FeatureX/featureX Navigation Graph
---
%%{init: {'theme':'base', 'themeVariables': { 'primaryTextColor': '#fff' }}%%
graph TD
feature_x/feature_x(["FeatureXGraph"]) -- "start" --- feature_x/feature_x_home("FeatureXHome")
feature_x/feature_x(["FeatureXGraph"]) --- feature_x/internal_args_screen("InternalArgsScreen")


classDef destination fill:#5383EC,stroke:#ffffff;
class feature_x/feature_x_home,feature_x/internal_args_screen destination;
classDef navgraph fill:#63BC76,stroke:#ffffff;
class feature_x/feature_x navgraph;
