---
title: MyTopLevel Navigation Graph
---
%%{init: {'theme':'base', 'themeVariables': { 'primaryTextColor': '#fff' }}%%
graph TD
my_top_level(["MyTopLevelGraph"]) -- "start" --- asd("Asd")


classDef destination fill:#5383EC,stroke:#ffffff;
class asd destination;
classDef navgraph fill:#63BC76,stroke:#ffffff;
class my_top_level navgraph;
