---
title: SubFeatureY/subFeatureY Navigation Graph
---
%%{init: {'theme':'base', 'themeVariables': { 'primaryTextColor': '#fff' }}%%
graph TD
sub_feature_y/sub_feature_y(["SubFeatureYGraph"]) -- "start" --- sub_feature_y/sub_feature_y_home("SubFeatureYHome")
sub_feature_y/sub_feature_y(["SubFeatureYGraph"]) --- sub_feature_y/sub_feature_y_internal_args_screen("SubFeatureYInternalArgsScreen")


classDef destination fill:#5383EC,stroke:#ffffff;
class sub_feature_y/sub_feature_y_home,sub_feature_y/sub_feature_y_internal_args_screen destination;
classDef navgraph fill:#63BC76,stroke:#ffffff;
class sub_feature_y/sub_feature_y navgraph;
