package com.ramcosta.composedestinations.codegen.templates.navtype.arrays


const val TYPE_ARG_CLASS_SIMPLE_NAME = "[TYPE_ARG_CLASS_SIMPLE_NAME]"
const val ARRAY_CUSTOM_NAV_TYPE_NAME = "[ARRAY_CUSTOM_NAV_TYPE_NAME]"
const val SERIALIZER_TYPE_ARG_CLASS_SIMPLE_NAME = "[SERIALIZER_TYPE_ARG_CLASS_SIMPLE_NAME]"
const val NAV_TYPE_INITIALIZATION_CODE = "[NAV_TYPE_INITIALIZATION_CODE]"