---
title: Root Navigation Graph
---
%%{init: {'theme':'base', 'themeVariables': { 'primaryTextColor': '#fff' }}%%
graph TD
root(["RootGraph"]) -- "start" --- greeting_screen("GreetingScreen")
root(["RootGraph"]) --- root/stats_screen("StatsScreen")
root(["RootGraph"]) --- root/profile_settings_screen("ProfileSettingsScreen")
root(["RootGraph"]) --- feed("Feed")
root(["RootGraph"]) --- go_to_profile_confirmation("GoToProfileConfirmation")
root(["RootGraph"]) --- test_screen("TestScreen")
root(["RootGraph"]) --- test_screen2("TestScreen2")
root(["RootGraph"]) --- test_screen3("TestScreen3")
root(["RootGraph"]) --- settings(["SettingsGraph"])
root(["RootGraph"]) --- profile(["ProfileGraph"])
settings(["SettingsGraph"]) -- "start" --- settings_screen("SettingsScreen")
settings(["SettingsGraph"]) --- settings/stats_screen("StatsScreen")
settings(["SettingsGraph"]) --- another_test_screen("AnotherTestScreen")
settings(["SettingsGraph"]) --- theme_settings("ThemeSettings")
settings(["SettingsGraph"]) --- other_activity("OtherActivity")
profile(["ProfileGraph"]) -- "start" --- profile_settings(["ProfileSettingsGraph"])
profile(["ProfileGraph"]) --- profile_screen("ProfileScreen")
profile(["ProfileGraph"]) --- public_feature_y_side_screen_destination("PublicFeatureYSideScreen 🧩")
profile(["ProfileGraph"]) --- feature_x_nav_g(["FeatureXGraph 🧩"])
profile(["ProfileGraph"]) --- feature_y_nav_g(["FeatureYGraph 🧩"])
profile_settings(["ProfileSettingsGraph"]) -- "start" --- profile_settings/profile_settings_screen("ProfileSettingsScreen")

click feature_x_nav_g "FeatureXNavGraph.mmd" "See FeatureXGraph details" _blank
click feature_y_nav_g "FeatureYNavGraph.mmd" "See FeatureYGraph details" _blank

classDef destination fill:#5383EC,stroke:#ffffff;
class root/stats_screen,root/profile_settings_screen,feed,go_to_profile_confirmation,test_screen,test_screen2,test_screen3,greeting_screen,settings/stats_screen,another_test_screen,settings_screen,theme_settings,other_activity,profile_screen,public_feature_y_side_screen_destination,profile_settings/profile_settings_screen destination;
classDef navgraph fill:#63BC76,stroke:#ffffff;
class settings,profile,root,settings,profile_settings,profile,feature_x_nav_g,feature_y_nav_g,profile_settings navgraph;
